parameters:
  name: ''
  formula: ''
  head: false

jobs:
- job: ${{ parameters.name }}
  strategy:
    matrix:
      HighSierra:
        VM_IMAGE: macOS-10.13
        XCODE_VERSION: '10.1'
      Mojave:
        VM_IMAGE: macOS-10.14
        XCODE_VERSION: '10.2'
  pool:
    vmImage: $(VM_IMAGE)
  steps:
  - script: sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
  - ${{ if eq(parameters.head, true) }}:
    - script: brew install --verbose --HEAD ./${{ parameters.formula }}.rb
  - ${{ if eq(parameters.head, false) }}:
    - script: brew install --verbose ./${{ parameters.formula }}.rb
